name: Build CraftGPT

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"
                  cache: "gradle"

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
              with:
                  gradle-version: 8.8
                  cache-read-only: ${{ github.ref != 'refs/heads/master' }}

            - name: Build with Gradle
              run: ./gradlew shadowJar --build-cache --parallel --configure-on-demand

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: CraftGPT
                  path: build/libs/*.jar
                  if-no-files-found: error
                  retention-days: 5
