name: Build CraftGPT

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21.0.5'
        distribution: 'oracle'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean shadowJar

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CraftGPT
        path: build/libs/*.jar
        if-no-files-found: error
